apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
        - name: survey-app
          image: qshahid/survey-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
