# Author: Qasim Shahid
# Deployment config for the survey app
# Sets up 3 replicas of our container to handle web traffic
# Uses our Docker Hub image that is updated on every push to main branch on GitHub: qshahid/survey-app

apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
        - name: survey-app
          image: qshahid/survey-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
