apiVersion: v1
kind: Service
metadata:
  name: survey-app-service
spec:
  selector:
    app: survey-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001 # App will be accessible at http://<node-ip>:30001
  type: NodePort